services:
 server:
  init: true
  ports:
   - name: zabbix-trapper
     target: 10051
     published: "${ZABBIX_SERVER_PORT}"
     protocol: tcp
     app_protocol: zabbix-trapper
  restart: "${RESTART_POLICY}"
  attach: true
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ${DATA_DIRECTORY}/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ${DATA_DIRECTORY}/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ${DATA_DIRECTORY}/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
   - ${DATA_DIRECTORY}/var/lib/zabbix/export:/var/lib/zabbix/export:rw
   - ${DATA_DIRECTORY}/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ${DATA_DIRECTORY}/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ${DATA_DIRECTORY}/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ${DATA_DIRECTORY}/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - snmptraps:/var/lib/zabbix/snmptraps:roz
  tmpfs: /tmp
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 1G
    reservations:
      cpus: '0.5'
      memory: 512M
  env_file:
   - ${ENV_VARS_DIRECTORY}/.env_srv
     required: false
  networks:
   frontend:
#  devices:
#   - "/dev/ttyUSB0:/dev/ttyUSB0"
  stop_grace_period: 30s
#  cap_add:
#    - "NET_RAW"
  sysctls:
   - net.ipv4.ip_local_port_range=1024 64999
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
#   - net.ipv4.ping_group_range=0 1995

 server-mysql:
  extends:
   service: server
#  volumes:
#   - dbsocket:/var/run/mysqld/
  env_file:
   - ${ENV_VARS_DIRECTORY}/.env_db_mysql
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
#   - client-key.pem
#   - client-cert.pem
#   - root-ca.pem
  networks:
   frontend:
     aliases:
      - zabbix-server-mysql


 proxy:
  init: true
  profiles:
   - all
  restart: "${RESTART_POLICY}"
  attach: false
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ${DATA_DIRECTORY}/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ${DATA_DIRECTORY}/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ${DATA_DIRECTORY}/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ${DATA_DIRECTORY}/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ${DATA_DIRECTORY}/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - snmptraps:/var/lib/zabbix/snmptraps:ro
  tmpfs: /tmp
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
    reservations:
      cpus: '0.3'
      memory: 256M
  env_file:
   - ${ENV_VARS_DIRECTORY}/.env_prx
  networks:
   frontend:
  stop_grace_period: 30s
#  cap_add:
#    - "NET_RAW"
  sysctls:
   - net.ipv4.ip_local_port_range=1024 64999
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
#   - net.ipv4.ping_group_range=0 1995

 proxy-mysql:
  extends:
   service: proxy
  ports:
   - name: zabbix-trapper
     target: 10051
     published: "${ZABBIX_PROXY_MYSQL_PORT}"
     protocol: tcp
     app_protocol: zabbix-trapper
#  volumes:
#   - dbsocket:/var/run/mysqld/
  env_file:
   - ${ENV_VARS_DIRECTORY}/.env_db_mysql_proxy
   - ${ENV_VARS_DIRECTORY}/.env_prx_mysql
     required: false
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
#   - client-key.pem
#   - client-cert.pem
#   - root-ca.pem
  networks:
   database:
     aliases:
      - zabbix-proxy-mysql
   frontend:
    aliases:
     - zabbix-proxy-mysql

 web-nginx:
  ports:
   - name: web-http
     target: 8080
     published: "${ZABBIX_WEB_NGINX_HTTP_PORT}"
     protocol: tcp
     app_protocol: http
   - name: web-https
     target: 8443
     published: "${ZABBIX_WEB_NGINX_HTTPS_PORT}"
     protocol: tcp
     app_protocol: https
  restart: "${RESTART_POLICY}"
  attach: false
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ${DATA_DIRECTORY}/etc/ssl/nginx:/etc/ssl/nginx:ro
   - ${DATA_DIRECTORY}/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
  tmpfs: /tmp
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
    reservations:
      cpus: '0.5'
      memory: 256M
  env_file:
   - ${ENV_VARS_DIRECTORY}/.env_web
     required: false
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  networks:
   frontend:
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535

 web-nginx-mysql:
  extends:
   service: web-nginx
#  volumes:
#   - dbsocket:/var/run/mysqld/
  env_file:
   - ${ENV_VARS_DIRECTORY}/.env_db_mysql
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
#   - client-key.pem
#   - client-cert.pem
#   - root-ca.pem
  networks:
   frontend:
    aliases:
     - zabbix-web-nginx-mysql

 agent:
  init: true
  profiles:
   - full
   - all
  ports:
   - name: zabbix-agent
     target: 10050
     published: "${ZABBIX_AGENT_PORT}"
     protocol: tcp
     app_protocol: zabbix-agent
  restart: "${RESTART_POLICY}"
  attach: false
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ${DATA_DIRECTORY}/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - ${DATA_DIRECTORY}/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ${DATA_DIRECTORY}/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ${DATA_DIRECTORY}/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
  tmpfs: /tmp
  deploy:
   resources:
    limits:
      cpus: '0.2'
      memory: 128M
    reservations:
      cpus: '0.1'
      memory: 64M
   mode: global
  env_file:
   - ${ENV_VARS_DIRECTORY}/.env_agent
     required: false
  privileged: true
  pid: "host"
  networks:
   frontend:
    aliases:
     - zabbix-agent
     - zabbix-agent-passive
  stop_grace_period: 5s

 agent2:
  init: true
  profiles:
   - full
   - all
  ports:
   - name: zabbix-agent
     target: 10050
     published: "${ZABBIX_AGENT2_PORT}"
     protocol: tcp
     app_protocol: zabbix-agent
  restart: "${RESTART_POLICY}"
  attach: false
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ${DATA_DIRECTORY}/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - ${DATA_DIRECTORY}/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ${DATA_DIRECTORY}/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ${DATA_DIRECTORY}/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
  tmpfs: /tmp
  deploy:
   resources:
    limits:
      cpus: '0.2'
      memory: 128M
    reservations:
      cpus: '0.1'
      memory: 64M
   mode: global
  env_file:
   - ${ENV_VARS_DIRECTORY}/.env_agent
     required: false
  privileged: true
  pid: "host"
  networks:
   frontend:
    aliases:
     - zabbix-agent
     - zabbix-agent-passive
  stop_grace_period: 5s

 web-service:
  profiles:
   - full
   - all
  ports:
   - name: zabbix-web-service
     target: 10053
     published: "${ZABBIX_WEB_SERVICE_PORT}"
     protocol: tcp
  restart: "${RESTART_POLICY}"
  attach: false
  volumes:
   - ${DATA_DIRECTORY}/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
  tmpfs: /tmp
  security_opt:
   - seccomp:${ENV_VARS_DIRECTORY}/chrome_dp.json
  deploy:
   resources:
    limits:
      cpus: '0.5'
      memory: 512M
    reservations:
      cpus: '0.25'
      memory: 256M
  env_file:
   - ${ENV_VARS_DIRECTORY}/.env_web_service
     required: false
  networks:
   frontend:
    aliases:
     - zabbix-web-service
  stop_grace_period: 5s
